version: 2
jobs:
  build:
    docker:
    - image: circleci/node:8.12
    working_directory: ~/repo
    steps:
    - attach_workspace:
        at: ~/repo
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: yarn install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: yarn coverage
    - run: yarn coveralls
    - store_artifacts:
        path: ./coverage/lcov.info
        prefix: tests
    - store_artifacts:
        path: coverage
        prefix: coverage
workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master
            - develop
            - /br-.*/